### PR TITLE
docs: generic asyncs state adapter demo

### PR DESCRIPTION
**Pull request by rodzappa**
Generic Async State Adaptor and Factory Service to show how to
use two or more separate async state adapters inside a component scope.

### CODE REVIEW

**Comment by rodzappa** [comment]
Hi @mfp22, I created this demo to show off how I have implemented state adapter im my project, handling async requests to update state store. The contents inside async-generic folder are generic enought to be consunmed by any projects and don't have any external dependencies.

My intent was allow various differents adapters from same type, inside an same scope. 
This is usefull when we deal with differents views, attached to different streams,  from a single entity type.

**Comment by rodzappa** [comment]
Let me know what you think about it.

**Comment by mfp22** [comment]
Hey @rodzappa , thanks for the PR! 

`AsyncEntity` was next on my roadmap, actually. There are a couple of differences between how I planned it and how you've implemented it here. You've got a couple of better ideas than the ones I had (for example, having `entity` as a property instead of spreading the object with the async properties like `loading`; it seems much cleaner). I am torn on naming though, because `@ngrx/entity` has `createEntityAdapter` (singular) and that is actually a list of entities. So I would have to break from their convention if I created both `asyncEntity` and `asyncEntities`. 

Currently I am working on the core documentation, but my next plan was to add an official library for adapters, which would include an async one, and then use it in the shopping demo app. I am doing documentation first because I have to do it eventually anyway, and it might be even faster for me to do than creating demo apps. 

The main issue I see in your PR is that usually with async state you already have an observable from an http request, so the more natural thing to do is to convert it into various sources rather than defining new sources entirely. If you look in the core library files, you'll see a `getHttpSources` function that is not documented yet. As soon as I finish this documentation I will let you know. My goal is today, but it could take a little longer. 

After I am done with this documentation I will give a more detailed feedback on this. 

As always, thanks for the help and let me know if you want to talk about anything.

**Comment by mfp22** [comment]
@rodzappa I just published the documentation for sources. Might work on the overview or adapters next. https://state-adapt.github.io/concepts/sources

**Comment by rodzappa** [comment]
Hi, @mfp22. I've read the documentantion for sources, but I'm busy mantaining a legacy system (What don't we do for living?). I'll still busy on it until the end of the month, althoug I hope will have some time to include getHttpSources in my implementation of state adapt. Until there, if you have some more docs or examples published, I'll appreciate to know that.

PS: Good luck with your home moving!

**Comment by mfp22** [comment]
@rodzappa Thank you. Things have gone pretty smoothly with the house, so I am happy.

I just published all the docs I was working on. I will add some diagrams here and there, or maybe not, but I think I got everything important in the docs now. I added a section at the bottom of `Sources`, and may have made a couple of other small changes too. https://state-adapt.github.io/concepts/overview

I am making a change to the API. After writing a few dozen adapters, I have started to hate writing selectors as a function with `getSelectors`. The docs have the updated syntax. The only reason I started it that way was to match the pattern established by @ngrx/entity and Redux's toolkit. However, I have already broken from @ngrx/entity with the state change functions by having the state be the first argument of all of them (it was necessary), so we cannot just use their entity adapter out of the box anyway. And I imagine people will be writing thousands of adapters in the future, so it seems unnecessary to match the API for their one adapter so closely. The reason they had selectors accessed by `getSelectors` was so developers could pass in the path selector, but in StateAdapt people are providing that with the state path in `.init()` so I am just attaching the adapter selectors onto that. We do not need it. 

I haven't released 0.38.0 yet but it will have this change in it. 

My next priorities are
- Publish 0.38.0 (with `getSelectors` => `selectors`)
- improve the design of the docs site a little bit
- start making the adapter creator library

After going over the whole API again while writing those docs, I feel like StateAdapt is getting very close to a 1.0.0 release.

**Comment by rodzappa** [comment]
@mfp22, I'll try a new approach after reading those docs and will send new PR after finishing.

**Pull request closed without merging**
