### PR TITLE
feat(docs): Example of using services with state adapt

### PR DESCRIPTION
**Pull request by rodzappa**
Motivation: To have one singleton state store shared across all
components

### CODE REVIEW

**Comment by rodzappa** [comment]
Hi @mfp22, this is a simple example how I'm using state-adapt organized in angular services. 
I'm using pure state-adapt (no ngrx or ngxs).
I've found an issue and will open a ticket to discuss it there, using this example as reference.

**Comment by mfp22** [comment]
@rodzappa First of all, thank you so much for helping. I am putting in a lot of time but there is only a certain amount one person can do. 

I think you are a little ahead of me here though. There are some things I haven't had time to explain or demo. One is the issue you just opened. But there are a couple of other things I have not yet shown in any documentation. Adapters should be exported alone and probably put in a file named `<adapter-name>.adapter.ts`. I also think the mini-stores and actions should be defined right in the service next to each other, if not in a component. I really wanted to get away from the global mindset of NgRx with StateAdapt, for everything except adapters. 

If you give me a day or two I will have another demo that involves a service so you can see what I am talking about. I should be able to create a very quick one, and if you want to add to it or change it I would appreciate it. I am just about done with my `shopping` demo app, which uses the `join` function, which nobody knows about yet unless they've read the source code. StateAdapt is not complete without it, so I wanted to put at least one thing out there with it. As soon as that is out, hopefully today, I will create a demo app with a service. 

If you ever want to chat, let me know. We can have a Zoom call or anything that you think would help.

**Comment by rodzappa** [comment]
@mfp22 I'd like so much to chat with you, although I think it will be more effective to wait you publish the new demo before. Meanwhile, I'll read the source code to try to understand the internals. Certainly it will emerge a lot of questions in my head, so it will be possible discuss them with you that moment.

**Comment by mfp22** [comment]
@rodzappa I have published the example using services. I decided to use services in my shopping demo app, so you can look there now. I am about to upload a video to YouTube where I talked through the process. It is a long video because I didn't solve anything beforehand. But if you have any thoughts or feedback on any of this, I would love to hear them. I will be publishing the YouTube video in the next 12 hours.

**Comment by mfp22** [comment]
@rodzappa Here's the video. Took a while to process https://www.youtube.com/watch?v=idb2eE-AdQA

**Comment by rodzappa** [comment]
Hi @mfp22, I've just watched the video and nevertheless it is unusual long, it was very helpfull to catch some of your insights about state-adapter. It was usefull watching you thinking loud. I've learnt a lot.

Now I've understood the real power of event sources (aka actions) as just observables and how is easy to bind them directly to a component event emitter. More important than implementation details are the concepts covered, although I've enjoyed so much seen them how they vave been implemented.

I just can imagine how much effort you have been investing on state-adapter and how rough was make this video, but the results are great. I thank you a lot for them.

I'll continue reporting my experience of using state-adapter in order to provide userful information to improve it.

PS: I've stopped using VSCode due to some annoying issues and poor angular template checking. I'm using Jetbrains IDEs (Webstorm and Intellij) and I have no regrets. However they are paid tools, but I think are worth.

**Comment by mfp22** [comment]
@rodzappa Yeah, sorry it was long. I just posted a follow-up video that's < 4 minutes though :) https://www.youtube.com/watch?v=y95FmQ4nztE

The benefit of wrapping sources in methods is it prevents the component from subscribing to the event source as a regular observable. But in my opinion it allows maybe too much room to code imperatively. One of my main goals is to bring the event emitters/subjects as close to the event source as possible to encourage the reactive mindset. But maybe there is a naming convention for sources that would help distinguish them from regular observables, like maybe appending `Source` instead of `$`. So like `quantityChangeSource` instead of `quantityChange$`. Or maybe `quantityChangeS`, or even just `quantityChange`. Any opinion on this?

Thank you, it makes me happy you find utility in StateAdapt. 

I thought I had found a perfect IDE in VSCode, and most of the shortcomings with inline templates have been with the Angular Language Service VSCode extension, not VSCode itself. But it would be really nice to get better support for inline templates. When I worked with Aaron Frost he actually preferred Webstorm over VSCode as well. Maybe I'll give it a try.

**Comment by rodzappa** [comment]
@mfp22 Sources, imho, are more like Action Dispatchers than just regular observers (subjects, in this case). Maybe, a name like" ActionDispatcher" or "EventStateChanger" or else "ActionSubject" could be easier to associate with theirs purpose (and easier to anothers redux tools users to understand).

I've just noted the last commit with joinSelectors implementation and state-adapter already appears good enought to start using.

Could you publish a new release on npm?

PS: I know that is too early to release a 1.0.0 version, due to the facts would be good to have unit tests in place, at least. I have some little experience with jest and nx workspace and I could start implementing some tests. If you had some ideas or guidelines about it, please, let me know.

**Comment by mfp22** [comment]
@rodzappa Yep, new release is on NPM now, version 0.37.0. I'm using it in [StackBlitz](https://stackblitz.com/github/state-adapt/state-adapt/tree/stackblitz-ng-sa-shopping?file=apps%2Fng-sa-shopping%2Fsrc%2Fapp%2Fapp.component.ts). Unfortunately it is going to take some work to get those SVGs to show up in StackBlitz though. 

I don't have any strong opinions about testing. I don't like boilerplate so I personally only write a lot of tests for pure functions because they're so straight-forward. So feel free to write whatever tests you want and to establish a pattern for testing going forward, if you want. I do have a test or two in `@state-adapt/core` and I like how I wrote them :) Still open to feedback of course

**Pull request closed without merging**
